<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserDetailsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('user_details')->insert([
            [
                'user_details_id' => 1,
                'user_id' => 1,
                'first_name' => 'System',
                'last_name' => 'Administrator',
                'phone' => '+1-800-555-0001',
                'address' => null,
                'city' => 'Toronto',
                'state' => 'Ontario',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => null,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 2,
                'user_id' => 2,
                'first_name' => 'John',
                'last_name' => 'Smith',
                'phone' => '+1-416-555-0101',
                'address' => null,
                'city' => 'Toronto',
                'state' => 'Ontario',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 85.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 3,
                'user_id' => 3,
                'first_name' => 'Sarah',
                'last_name' => 'Jones',
                'phone' => '+1-604-555-0102',
                'address' => null,
                'city' => 'Vancouver',
                'state' => 'British Columbia',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 90.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 4,
                'user_id' => 4,
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'phone' => '+1-403-555-0103',
                'address' => null,
                'city' => 'Calgary',
                'state' => 'Alberta',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 80.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 5,
                'user_id' => 5,
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'phone' => '+1-514-555-0104',
                'address' => null,
                'city' => 'Montreal',
                'state' => 'Quebec',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 85.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 6,
                'user_id' => 6,
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'phone' => '+1-416-555-0105',
                'address' => null,
                'city' => 'Toronto',
                'state' => 'Ontario',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 90.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 7,
                'user_id' => 7,
                'first_name' => 'Lisa',
                'last_name' => 'Martinez',
                'phone' => '+1-604-555-0106',
                'address' => null,
                'city' => 'Vancouver',
                'state' => 'British Columbia',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 95.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 8,
                'user_id' => 8,
                'first_name' => 'Robert',
                'last_name' => 'Anderson',
                'phone' => '+1-403-555-0107',
                'address' => null,
                'city' => 'Calgary',
                'state' => 'Alberta',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 100.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ],
            [
                'user_details_id' => 9,
                'user_id' => 9,
                'first_name' => 'Jennifer',
                'last_name' => 'Taylor',
                'phone' => '+1-416-555-0108',
                'address' => null,
                'city' => 'Toronto',
                'state' => 'Ontario',
                'postal_code' => null,
                'country' => 'Canada',
                'profile_image' => null,
                'bio' => null,
                'linkedin_url' => null,
                'website_url' => null,
                'resume_or_cv' => null,
                'hourly_rate' => 75.00,
                'availability_status' => 'Available',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-07 18:48:50'
            ]
        ]);
    }
}
