<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // Admin User
            [
                'user_id' => 1,
                'email' => 'admin@geospace.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 1,
                'user_position' => 'System Administrator',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Freelancers
            [
                'user_id' => 2,
                'email' => 'john.smith@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Senior Geologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'email' => 'sarah.jones@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Geophysicist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'email' => 'michael.brown@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Geological Engineer',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'email' => 'emily.davis@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Mining Geologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'email' => 'david.wilson@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Environmental Geologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'email' => 'lisa.martinez@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Hydrogeologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'email' => 'robert.anderson@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Petroleum Geologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'email' => 'jennifer.taylor@gmail.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 2,
                'user_position' => 'Engineering Geologist',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Company Users
            [
                'user_id' => 10,
                'email' => 'contact@northernmining.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'HR Manager',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 11,
                'email' => 'info@geodata.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'Project Manager',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'email' => 'hr@explorationcorp.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'Operations Manager',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'email' => 'admin@geoservices.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'Director',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'email' => 'contact@mineralsolutions.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'CEO',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 15,
                'email' => 'info@earthtech.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'VP Operations',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'email' => 'hr@geologyconsult.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'HR Director',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'email' => 'contact@resourcegroup.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 3,
                'user_position' => 'Project Lead',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Support Users
            [
                'user_id' => 18,
                'email' => 'support1@geospace.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 4,
                'user_position' => 'Support Agent',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'email' => 'support2@geospace.com',
                'password_hash' => Hash::make('password'),
                'role_id' => 4,
                'user_position' => 'Senior Support Agent',
                'is_active' => true,
                'is_verified' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
