<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'user_id' => 1,
                'email' => 'admin@geospace.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 1,
                'user_position' => 'System Administrator',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => '2025-10-10 23:53:53',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-10 23:53:53'
            ],
            [
                'user_id' => 2,
                'email' => 'john.smith@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Senior Geologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => '2025-10-08 05:09:19',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 05:09:19'
            ],
            [
                'user_id' => 3,
                'email' => 'sarah.jones@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Geophysicist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 4,
                'email' => 'michael.brown@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Geological Engineer',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 5,
                'email' => 'emily.davis@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Mining Geologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 6,
                'email' => 'david.wilson@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Environmental Geologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 7,
                'email' => 'lisa.martinez@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Hydrogeologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 8,
                'email' => 'robert.anderson@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Petroleum Geologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 9,
                'email' => 'jennifer.taylor@gmail.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 2,
                'user_position' => 'Engineering Geologist',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 10,
                'email' => 'contact@northernmining.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'HR Manager',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => '2025-10-08 10:28:53',
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 10:28:53'
            ],
            [
                'user_id' => 11,
                'email' => 'info@geodata.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'Project Manager',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 12,
                'email' => 'hr@explorationcorp.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'Operations Manager',
                'auth_provider' => null,
                'is_active' => 0,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:07:55'
            ],
            [
                'user_id' => 13,
                'email' => 'admin@geoservices.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'Director',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 14,
                'email' => 'contact@mineralsolutions.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'CEO',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 15,
                'email' => 'info@earthtech.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'VP Operations',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 16,
                'email' => 'hr@geologyconsult.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'HR Director',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 17,
                'email' => 'contact@resourcegroup.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 3,
                'user_position' => 'Project Lead',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 18,
                'email' => 'support1@geospace.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 4,
                'user_position' => 'Support Agent',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ],
            [
                'user_id' => 19,
                'email' => 'support2@geospace.com',
                'password_hash' => '$2y$12$Q9q5VZONH5hja3WRMhuBNO6dPZJyklSgXrKaozlNBJxBCBneEStsK',
                'role_id' => 4,
                'user_position' => 'Senior Support Agent',
                'auth_provider' => null,
                'is_active' => 1,
                'is_verified' => 1,
                'email_verified_at' => '2025-10-07 18:48:50',
                'last_login' => null,
                'created_at' => '2025-10-07 18:48:50',
                'updated_at' => '2025-10-08 11:06:00'
            ]
        ]);
    }
}
