<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'project_id' => 1,
                'company_id' => 10, // Northern Mining Corp
                'project_title' => 'Northern Gold Exploration Project',
                'project_description' => 'Comprehensive geological exploration project in Northern Ontario to identify and evaluate gold mineralization potential in the region.',
                'project_category' => 'Mineral Exploration',
                'budget_min' => 500000.00,
                'budget_max' => 1500000.00,
                'start_date' => '2025-01-15',
                'end_date' => '2025-12-31',
                'location' => 'Red Lake, Ontario, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Geological Mapping, Core Logging, Resource Estimation, ArcGIS, Leapfrog',
                'experience_level' => 'Expert',
                'estimated_duration' => 12,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'company_id' => 11, // GeoData Analytics
                'project_title' => 'Geospatial Data Analysis for Mining Operations',
                'project_description' => 'Advanced geospatial analysis and modeling for optimizing mining operations using GIS and remote sensing data.',
                'project_category' => 'Geospatial Analysis',
                'budget_min' => 200000.00,
                'budget_max' => 800000.00,
                'start_date' => '2025-02-01',
                'end_date' => '2025-08-31',
                'location' => 'Vancouver, BC, Canada',
                'status' => 'In Progress',
                'required_skills' => 'ArcGIS, QGIS, Python, R, Remote Sensing, Geospatial Analysis',
                'experience_level' => 'Expert',
                'estimated_duration' => 7,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 3,
                'company_id' => 12, // Exploration Corp International
                'project_title' => 'Copper-Nickel Exploration in Northern Quebec',
                'project_description' => 'Large-scale exploration project targeting copper-nickel deposits in the Canadian Shield region of Northern Quebec.',
                'project_category' => 'Mineral Exploration',
                'budget_min' => 1000000.00,
                'budget_max' => 3000000.00,
                'start_date' => '2025-03-01',
                'end_date' => '2025-02-28',
                'location' => 'Chibougamau, Quebec, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Geological Mapping, Core Logging, Geochemistry, Structural Geology, Mine Planning',
                'experience_level' => 'Expert',
                'estimated_duration' => 12,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 4,
                'company_id' => 13, // Geo Services Ltd
                'project_title' => 'Environmental Impact Assessment for Mining Project',
                'project_description' => 'Comprehensive environmental impact assessment for a proposed mining operation, including water quality, soil contamination, and remediation planning.',
                'project_category' => 'Environmental Assessment',
                'budget_min' => 150000.00,
                'budget_max' => 500000.00,
                'start_date' => '2025-01-01',
                'end_date' => '2025-06-30',
                'location' => 'Montreal, QC, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Environmental Monitoring, Water Quality Assessment, Soil Contamination Assessment, Remediation Planning',
                'experience_level' => 'Expert',
                'estimated_duration' => 6,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 5,
                'company_id' => 14, // Mineral Solutions Inc
                'project_title' => 'Diamond Exploration in Northern Canada',
                'project_description' => 'High-potential diamond exploration project in the Northwest Territories, focusing on kimberlite pipe identification and evaluation.',
                'project_category' => 'Mineral Exploration',
                'budget_min' => 800000.00,
                'budget_max' => 2000000.00,
                'start_date' => '2025-04-01',
                'end_date' => '2025-03-31',
                'location' => 'Yellowknife, NWT, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Geological Mapping, Core Logging, Mineralogy, Petrology, Geochemistry',
                'experience_level' => 'Expert',
                'estimated_duration' => 12,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 6,
                'company_id' => 15, // EarthTech Engineering
                'project_title' => 'Geotechnical Investigation for Infrastructure Project',
                'project_description' => 'Comprehensive geotechnical investigation for a major infrastructure project, including foundation design and slope stability analysis.',
                'project_category' => 'Geotechnical Engineering',
                'budget_min' => 300000.00,
                'budget_max' => 750000.00,
                'start_date' => '2025-02-15',
                'end_date' => '2025-09-30',
                'location' => 'Vancouver, BC, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Geological Mapping, Structural Geology, Geotechnical Analysis, AutoCAD, ArcGIS',
                'experience_level' => 'Expert',
                'estimated_duration' => 8,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 7,
                'company_id' => 16, // Geology Consultants
                'project_title' => 'Petroleum Geology Assessment for Oil Sands',
                'project_description' => 'Detailed petroleum geology assessment for oil sands development in Alberta, including reservoir characterization and production optimization.',
                'project_category' => 'Petroleum Geology',
                'budget_min' => 400000.00,
                'budget_max' => 1200000.00,
                'start_date' => '2025-01-01',
                'end_date' => '2025-12-31',
                'location' => 'Calgary, AB, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Petroleum Geology, Well Logging, Reservoir Characterization, Seismic Data Processing, Python',
                'experience_level' => 'Expert',
                'estimated_duration' => 12,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 8,
                'company_id' => 17, // Resource Exploration Group
                'project_title' => 'Rare Earth Elements Exploration',
                'project_description' => 'Exploration project targeting rare earth elements in the Canadian Shield, focusing on critical mineral supply chain development.',
                'project_category' => 'Mineral Exploration',
                'budget_min' => 600000.00,
                'budget_max' => 1800000.00,
                'start_date' => '2025-03-15',
                'end_date' => '2025-03-14',
                'location' => 'Sudbury, Ontario, Canada',
                'status' => 'In Progress',
                'required_skills' => 'Geological Mapping, Core Logging, Geochemistry, Mineralogy, Resource Estimation',
                'experience_level' => 'Expert',
                'estimated_duration' => 12,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 9,
                'company_id' => 10, // Northern Mining Corp
                'project_title' => 'Mine Safety and Environmental Compliance Audit',
                'project_description' => 'Comprehensive audit of mine safety protocols and environmental compliance for existing mining operations.',
                'project_category' => 'Safety & Compliance',
                'budget_min' => 100000.00,
                'budget_max' => 300000.00,
                'start_date' => '2025-05-01',
                'end_date' => '2025-08-31',
                'location' => 'Red Lake, Ontario, Canada',
                'status' => 'Open',
                'required_skills' => 'Mine Safety, Environmental Impact Assessment, Environmental Monitoring, Compliance Auditing',
                'experience_level' => 'Expert',
                'estimated_duration' => 4,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 10,
                'company_id' => 11, // GeoData Analytics
                'project_title' => 'Machine Learning for Mineral Exploration',
                'project_description' => 'Development of machine learning algorithms for automated mineral exploration and target identification.',
                'project_category' => 'Technology Development',
                'budget_min' => 250000.00,
                'budget_max' => 600000.00,
                'start_date' => '2025-06-01',
                'end_date' => '2025-12-31',
                'location' => 'Vancouver, BC, Canada',
                'status' => 'Open',
                'required_skills' => 'Python, R, Machine Learning, ArcGIS, QGIS, Geospatial Analysis',
                'experience_level' => 'Expert',
                'estimated_duration' => 7,
                'duration_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('projects')->insert($projects);
    }
}
