-- Insert freelancer user details with correct user_ids
INSERT INTO user_details (user_id, first_name, last_name, phone, address, city, state, postal_code, country, profile_image, bio, linkedin_url, website_url, resume_or_cv, hourly_rate, availability_status) VALUES
(6, 'Sarah', 'Johnson', '+1-416-555-0101', '123 Geology Ave', 'Toronto', 'Ontario', 'M5V 3A8', 'Canada', '/images/profiles/sarah_johnson.jpg', 'Experienced geologist with 8+ years in mineral exploration and resource evaluation. Specialized in structural geology and ore deposit modeling.', 'https://linkedin.com/in/sarahjohnson', 'https://sarahgeology.com', '/resumes/sarah_johnson_cv.pdf', 85.00, 'Available'),
(7, 'Mike', 'Thompson', '+1-604-555-0102', '456 Mining Road', 'Vancouver', 'British Columbia', 'V6B 1A1', 'Canada', '/images/profiles/mike_thompson.jpg', 'Mining engineer with expertise in underground operations and safety protocols. 10+ years experience in gold and copper mining.', 'https://linkedin.com/in/mikethompson', NULL, '/resumes/mike_thompson_cv.pdf', 95.00, 'Available'),
(8, 'Emma', 'Davis', '+1-403-555-0103', '789 Environmental St', 'Calgary', 'Alberta', 'T2P 1J9', 'Canada', '/images/profiles/emma_davis.jpg', 'Environmental specialist focused on mining impact assessment and remediation. Certified in environmental management systems.', 'https://linkedin.com/in/emmadavis', 'https://emmadavis.ca', '/resumes/emma_davis_cv.pdf', 75.00, 'Available'),
(9, 'Alex', 'Rodriguez', '+1-514-555-0104', '321 Geophysics Blvd', 'Montreal', 'Quebec', 'H3A 0G4', 'Canada', '/images/profiles/alex_rodriguez.jpg', 'Geophysicist specializing in seismic interpretation and gravity surveys. Expert in data processing and geological modeling software.', 'https://linkedin.com/in/alexrodriguez', NULL, '/resumes/alex_rodriguez_cv.pdf', 90.00, 'Busy'),
(10, 'Lisa', 'Chen', '+1-780-555-0105', '654 Petroleum Way', 'Edmonton', 'Alberta', 'T5J 0N3', 'Canada', '/images/profiles/lisa_chen.jpg', 'Petroleum engineer with extensive experience in reservoir engineering and drilling operations. PhD in Petroleum Engineering.', 'https://linkedin.com/in/lisachen', 'https://lisachen-consulting.com', '/resumes/lisa_chen_cv.pdf', 110.00, 'Available'),
(11, 'David', 'Wilson', '+1-306-555-0106', '987 Hydro Lane', 'Saskatoon', 'Saskatchewan', 'S7K 3J7', 'Canada', '/images/profiles/david_wilson.jpg', 'Hydrogeologist with 6+ years experience in groundwater assessment and contamination studies. Specialized in mining hydrology.', 'https://linkedin.com/in/davidwilson', NULL, '/resumes/david_wilson_cv.pdf', 80.00, 'Unavailable'),
(12, 'Maria', 'Garcia', '+1-204-555-0107', '147 GIS Street', 'Winnipeg', 'Manitoba', 'R3C 0V8', 'Canada', '/images/profiles/maria_garcia.jpg', 'GIS specialist with expertise in spatial analysis and geological mapping. Proficient in ArcGIS, QGIS, and remote sensing technologies.', 'https://linkedin.com/in/mariagarcia', 'https://mariagisgeo.com', '/resumes/maria_garcia_cv.pdf', 70.00, 'Available'),
(13, 'James', 'Brown', '+1-709-555-0108', '258 Drilling Ave', 'St. Johns', 'Newfoundland and Labrador', 'A1C 5M5', 'Canada', '/images/profiles/james_brown.jpg', 'Drilling supervisor with 12+ years in diamond drilling and exploration. Certified in safety management and equipment operation.', 'https://linkedin.com/in/jamesbrown', NULL, '/resumes/james_brown_cv.pdf', 100.00, 'Available');

-- Insert company details with correct user_ids
INSERT INTO company_details (user_id, company_name, company_type, industry, company_size, website, description, founded_year, headquarters, logo) VALUES
(14, 'Gold Mining Corporation', 'Private Corporation', 'Mining', '201-500', 'https://goldminingcorp.com', 'Leading gold mining company with operations across North America. Committed to sustainable mining practices and community development.', 1995, 'Toronto, Ontario, Canada', '/images/logos/goldmining_corp.png'),
(15, 'Energy Explorers Ltd.', 'Limited Company', 'Oil & Gas', '51-200', 'https://energyexplorers.com', 'Innovative energy exploration company specializing in unconventional oil and gas resources. Focus on advanced drilling technologies.', 2008, 'Calgary, Alberta, Canada', '/images/logos/energy_explorers.png'),
(16, 'Mineral Tech Solutions', 'Corporation', 'Consulting', '11-50', 'https://mineraltech.com', 'Specialized consulting firm providing geological and mining engineering services to the mineral exploration industry.', 2012, 'Vancouver, British Columbia, Canada', '/images/logos/mineral_tech.png'),
(17, 'GeoSolutions Inc.', 'Incorporated', 'Geosciences', '51-200', 'https://geosolutions.com', 'Full-service geoscience company offering geological, geophysical, and environmental consulting services to mining and energy sectors.', 2005, 'Montreal, Quebec, Canada', '/images/logos/geosolutions.png');

-- Update existing users with proper names
UPDATE user_details SET first_name = 'Admin', last_name = 'User' WHERE user_id = 1;
UPDATE user_details SET first_name = 'John', last_name = 'Smith' WHERE user_id = 2;
UPDATE user_details SET first_name = 'Jane', last_name = 'Doe' WHERE user_id = 3;
UPDATE user_details SET first_name = 'Support', last_name = 'Agent' WHERE user_id = 4;
